[general]
import = [
    "~/.config/alacritty/themes/themes/{theme}.toml"
]

[env]
TERM = "xterm-256color"

[shell]
args = ['--login']
program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "0xProto Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.7
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[window.padding]
x = 9
y = 9

#[window.dimensions]
#columns = 90
#lines = 25

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"




