require("akito.core.keymaps")
require("akito.options.option")
require("akito.setup")
require("akito.plugins.lsp.mason")
require("akito.plugins.lsp.lspconfig")
require("akito.plugins.lsp.conform")
require("akito.plugins.lsp.lspsaga")
require("akito.plugins.neotree")
require("akito.plugins.barbar")
require("akito.plugins.nvimtmuxnavigation")
require("akito.plugins.cmp")
require("akito.plugins.gitsigns")
require("akito.plugins.lualine")
require("akito.plugins.catpuccin")
-- require("akito.plugins.noneckpain")
