require("akito.core.global")
require("akito.options.option")
require("akito.setup")
require("akito.core.keymaps")
require("akito.options.colorscheme")
require("akito.plugins.lsp.lspconfig")
require("akito.plugins.nvimtmuxnavigation")
require("akito.plugins.cmp")
require("akito.plugins.gitsigns")
require("akito.plugins.neocodeium")
-- require("akito.plugins.catpuccin")
-- require("akito.plugins.noneckpain")

